### ISSUE TITLE
[BUG] - Missing `escape_template/3` for `:make_binary`

### ISSUE THREAD

**Issue by RodolfoSilva** [hansihe/live_data#21]
If you try to concatenate a string inside the map, the application will crash.

```ex
defmodule MyAppWeb.HelloData do
  use LiveData

  def mount(_params, socket) do
    {:ok, assign(socket, :counter, 10)}
  end

  deft render(assigns) do
    %{
      hello: "number #{assigns.counter}"
    }
  end
end
```

This approach does not work, the escape_template for :make_binary is missing.

**Comment by hansihe** [comment]
Thanks for the report! I'll try to fix this relatively soon. If you would like to contribute a fix, that would of course be very welcome too.

**Comment by RodolfoSilva** [comment]
I have no idea how I can solve this problem. I'm not familiar with ASTs.... 🤣

**Comment by hansihe** [comment]
This should be fixed in https://github.com/hansihe/live_data/commit/1527dff4a94ac859335e10a70e49886252ddc05a
